### ISSUE TITLE
Install > Data Directory should be emphasized

### ISSUE THREAD

**Issue by sbrickey** [IvanJosipovic/AutoSPInstallerOnline#1]
For farms with search, the data directory is also used by the analytics component (REGARDLESS of index location), which Microsoft recommends have 300gb free.

Recommend that the directory have some sort of emphasis or note, to highlight the impact.

Especially if the index is in a non-default location (perhaps a second note below the index location, when non-default, indicating that the data folder should also be changed)

ref: http://blogs.msdn.com/b/chandru/archive/2013/08/15/analytics-component-disk-location-in-sp2013.aspx
ref: http://blogs.msdn.com/b/kristopherloranger/archive/2014/02/07/sharepoint-2013-search-io-critical-component-locations.aspx
(also confirmed with MS that this has not changed, as of Oct 02 2015)

**Comment by IvanJosipovic** [comment]
Thank you, I'll make sure to update the description in the next release.
