### ISSUE TITLE
MinRoles Single-server farm setting is not included in config XML

### ISSUE THREAD

**Issue by softwarecraft** [IvanJosipovic/AutoSPInstallerOnline#2]
When I use "Load from my XML" to retrieve the config I saved earlier today, the MinRoles section of the config is not loaded / or was not previously saved, so there is a warning and I have to reset this config point. I'm using Dev & Test: SIngle-server Farm. When I fix this and then inspect the config in Review & Download, I don't see anything in the XML to indicate this config point.

**Comment by IvanJosipovic** [comment]
This should be fixed now, thank you for the report.
